title: "My Tech Adventures"
author: "Deepak Chethan"
description: "A boring blog about interesting stuff!"
lang: "en"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 8                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false         # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
dark_theme: false            # enable dark mode
dark_header: true           # keep the header dark

navigation:                  # (optional) site navigation in the header
  - index.html

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "deepakchethan@outlook.com"
  github: "https://github.com/deepakchethan"
  linkedin: "https://www.linkedin.com/in/dpak-chtan"
  twitter: "https://www.twitter.com/deepakchethan"

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
